import fs from "node:fs/promises";
import path from "node:path";
import { nanoid } from "nanoid";
import { refsDir } from "@/lib/db";

export type ProviderName = "upload" | "stock" | "generated";

export interface SaveResult {
  filePath: string;     // absolute on disk
  publicPath: string;   // /api/refs/<name> — served by the route, not Next.js statics
  width?: number;
  height?: number;
  mime: string;
}

async function ensureDir() {
  await fs.mkdir(refsDir(), { recursive: true });
}

export async function saveUploadedImage(brandSlug: string, file: { name: string; mime: string; bytes: Buffer }): Promise<SaveResult> {
  await ensureDir();
  const ext = inferExt(file.mime, file.name);
  const id = nanoid(10);
  const rel = `${brandSlug}-${id}${ext}`;
  const abs = path.join(refsDir(), rel);
  await fs.writeFile(abs, file.bytes);
  return { filePath: abs, publicPath: `/api/refs/${rel}`, mime: file.mime };
}

// Pexels stock fetch (behind PEXELS_API_KEY).
// Returns the bytes; caller persists.
export interface StockResult {
  bytes: Buffer;
  mime: string;
  source: "pexels";
  prompt: string;
  attribution: string;
  width: number;
  height: number;
}

// List Pexels search results (no bytes yet — for an in-app picker). Returns
// thumbnail + full URLs so the client can show options and the server can
// download the chosen one in pickStockAction (#57).
export interface PexelsPhoto {
  id: number;
  alt: string;
  photographer: string;
  thumbUrl: string;
  fullUrl: string;
  width: number;
  height: number;
}

export async function pexelsList(query: string, opts: { limit?: number; orientation?: "landscape" | "portrait" | "square" } = {}): Promise<PexelsPhoto[]> {
  const key = process.env.PEXELS_API_KEY;
  if (!key) return [];
  const params = new URLSearchParams({ query: query.trim(), per_page: String(Math.min(Math.max(opts.limit || 12, 1), 30)) });
  if (opts.orientation) params.set("orientation", opts.orientation);
  const r = await fetch(`https://api.pexels.com/v1/search?${params}`, { headers: { Authorization: key } });
  if (!r.ok) return [];
  const j: any = await r.json();
  const photos: any[] = Array.isArray(j?.photos) ? j.photos : [];
  return photos.map((p) => ({
    id: p.id,
    alt: p.alt || "",
    photographer: p.photographer || "Pexels",
    thumbUrl: p.src?.medium || p.src?.small || p.src?.tiny || "",
    fullUrl: p.src?.large2x || p.src?.large || p.src?.original || "",
    width: p.width || 1200,
    height: p.height || 800,
  })).filter((p) => p.thumbUrl && p.fullUrl);
}

// Download bytes from any image URL — used to persist a chosen stock photo or
// a generated image into the brand's references.
export async function downloadImageBytes(url: string): Promise<{ bytes: Buffer; mime: string } | null> {
  try {
    const r = await fetch(url);
    if (!r.ok) return null;
    const ab = await r.arrayBuffer();
    const mime = r.headers.get("content-type") || "image/jpeg";
    return { bytes: Buffer.from(ab), mime };
  } catch { return null; }
}

export async function searchStock(query: string, orientation: "landscape" | "portrait" | "square" = "landscape"): Promise<StockResult | null> {
  const key = process.env.PEXELS_API_KEY;
  if (!key) return null;
  const url = `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=1&orientation=${orientation}`;
  const r = await fetch(url, { headers: { Authorization: key } });
  if (!r.ok) return null;
  const j: any = await r.json();
  const photo = j?.photos?.[0];
  if (!photo) return null;
  const dl = photo?.src?.large2x || photo?.src?.large || photo?.src?.original;
  if (!dl) return null;
  const imgResp = await fetch(dl);
  if (!imgResp.ok) return null;
  const ab = await imgResp.arrayBuffer();
  return {
    bytes: Buffer.from(ab),
    mime: "image/jpeg",
    source: "pexels",
    prompt: query,
    attribution: photo.photographer ? `Photo by ${photo.photographer} on Pexels` : "Pexels",
    width: photo.width || 1200,
    height: photo.height || 800,
  };
}

// Gemini generative path (behind GEMINI_API_KEY).
// Returns generated bytes for the requested aspect.
export interface GeneratedResult {
  bytes: Buffer;
  mime: string;
  source: "gemini";
  prompt: string;
  width: number;
  height: number;
}

// Models tried in order. First one with quota wins. Override or extend via env.
function imageModelChain(): string[] {
  const raw = process.env.GEMINI_IMAGE_MODEL_CHAIN || process.env.GEMINI_IMAGE_MODEL || "gemini-3.1-flash-image-preview,gemini-2.5-flash-image-preview,imagen-3.0-generate-002";
  return raw.split(",").map((s) => s.trim()).filter(Boolean);
}

async function callGemini(model: string, key: string, prompt: string): Promise<{ bytes: Buffer; mime: string } | { error: string }> {
  // Imagen uses :predict, Gemini image uses :generateContent
  const isImagen = model.startsWith("imagen");
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:${isImagen ? "predict" : "generateContent"}?key=${key}`;
  const body = isImagen
    ? { instances: [{ prompt }], parameters: { sampleCount: 1 } }
    : {
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: { responseModalities: ["IMAGE"] },
      };
  const r = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  if (!r.ok) {
    const txt = await r.text();
    return { error: `${r.status}: ${txt.slice(0, 240)}` };
  }
  const j: any = await r.json();
  if (isImagen) {
    const pred = j?.predictions?.[0];
    const b64 = pred?.bytesBase64Encoded;
    if (!b64) return { error: "imagen: no bytesBase64Encoded in response" };
    return { bytes: Buffer.from(b64, "base64"), mime: pred?.mimeType || "image/png" };
  }
  const part = j?.candidates?.[0]?.content?.parts?.find((p: any) => p?.inlineData?.data);
  if (!part) return { error: "gemini: no inlineData in response" };
  return { bytes: Buffer.from(part.inlineData.data, "base64"), mime: part.inlineData.mimeType || "image/png" };
}

export async function generateImage(prompt: string, aspectHint: string): Promise<GeneratedResult | null> {
  const key = process.env.GEMINI_API_KEY;
  if (!key) return null;
  const chain = imageModelChain();
  // Lock the output to editorial photography. The Coursera demo (and the Vision
  // QC critic) kept flagging abstract / 3D / illustrated outputs — these guards
  // belong here too, in case a caller's prompt is softer than the art director's.
  const fullPrompt = `${prompt}

Aspect ratio: ${aspectHint}.
EDITORIAL PHOTOGRAPHY. A real photograph of a real subject in a real environment, documentary or editorial style. Natural or studio-realistic light.
Do NOT produce: illustration, 3D, CGI, render, vector, low-poly, isometric, anime, cartoon, painted, line art, abstract gradients, geometric patterns, particle effects, glowing UI surfaces, generic stock-icon clutter.
Single image. No on-image text, no logos, no watermark.`;

  let lastError: string | null = null;
  for (const model of chain) {
    try {
      const out = await callGemini(model, key, fullPrompt);
      if ("error" in out) {
        console.warn(`[image] ${model} → ${out.error}`);
        lastError = out.error;
        continue;
      }
      const [aw, ah] = parseAspect(aspectHint);
      return { bytes: out.bytes, mime: out.mime, source: "gemini", prompt, width: aw, height: ah };
    } catch (e: any) {
      console.warn(`[image] ${model} threw:`, e?.message || e);
      lastError = e?.message || String(e);
    }
  }
  if (lastError) console.warn(`[image] all providers failed. last: ${lastError}`);
  return null;
}

export function geminiStatus(): { enabled: boolean; model: string; reason?: string } {
  if (!process.env.GEMINI_API_KEY) return { enabled: false, model: process.env.GEMINI_IMAGE_MODEL || "gemini-3.1-flash-image-preview", reason: "GEMINI_API_KEY not set" };
  return { enabled: true, model: process.env.GEMINI_IMAGE_MODEL || "gemini-3.1-flash-image-preview" };
}

export function pexelsStatus(): { enabled: boolean; reason?: string } {
  if (!process.env.PEXELS_API_KEY) return { enabled: false, reason: "PEXELS_API_KEY not set" };
  return { enabled: true };
}

export function figmaStatus(): { enabled: boolean; reason?: string } {
  if (!process.env.FIGMA_PERSONAL_ACCESS_TOKEN) return { enabled: false, reason: "FIGMA_PERSONAL_ACCESS_TOKEN not set" };
  return { enabled: true };
}

export async function saveBytes(brandSlug: string, bytes: Buffer, mime: string): Promise<SaveResult> {
  await ensureDir();
  const ext = inferExt(mime);
  const rel = `${brandSlug}-${nanoid(10)}${ext}`;
  const abs = path.join(refsDir(), rel);
  await fs.writeFile(abs, bytes);
  return { filePath: abs, publicPath: `/api/refs/${rel}`, mime };
}

function inferExt(mime: string, name?: string): string {
  if (name && /\.(png|jpe?g|webp|gif|avif|svg)$/i.test(name)) return name.match(/\.[a-z0-9]+$/i)![0].toLowerCase();
  if (mime.includes("svg")) return ".svg";
  if (mime.includes("png")) return ".png";
  if (mime.includes("webp")) return ".webp";
  if (mime.includes("gif")) return ".gif";
  if (mime.includes("avif")) return ".avif";
  return ".jpg";
}

// Minimal SVG hardening for operator-uploaded brand assets: drop scripts, event
// handlers, external/js URLs, and foreignObject. Not a full sanitizer, but
// removes the common XSS vectors before we ever serve or inline the file.
export function sanitizeSvg(svg: string): string {
  return svg
    .replace(/<\s*script[\s\S]*?<\s*\/\s*script\s*>/gi, "")
    .replace(/<\s*foreignObject[\s\S]*?<\s*\/\s*foreignObject\s*>/gi, "")
    .replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, "")
    .replace(/(href|xlink:href)\s*=\s*("javascript:[^"]*"|'javascript:[^']*')/gi, "")
    .replace(/<!ENTITY[\s\S]*?>/gi, "");
}

function parseAspect(a: string): [number, number] {
  const m = a.match(/(\d+(?:\.\d+)?):(\d+(?:\.\d+)?)/);
  if (!m) return [1200, 1200];
  const w = parseFloat(m[1]); const h = parseFloat(m[2]);
  const scale = 1200 / Math.max(w, h);
  return [Math.round(w * scale), Math.round(h * scale)];
}
