import fs from "node:fs/promises";
import path from "node:path";
import { nanoid } from "nanoid";

export type ProviderName = "upload" | "stock" | "generated";

export interface SaveResult {
  filePath: string;     // absolute on disk under /public/refs/
  publicPath: string;   // /refs/...
  width?: number;
  height?: number;
  mime: string;
}

const REFS_DIR = path.join(process.cwd(), "public", "refs");

async function ensureDir() {
  await fs.mkdir(REFS_DIR, { recursive: true });
}

export async function saveUploadedImage(brandSlug: string, file: { name: string; mime: string; bytes: Buffer }): Promise<SaveResult> {
  await ensureDir();
  const ext = inferExt(file.mime, file.name);
  const id = nanoid(10);
  const rel = `${brandSlug}-${id}${ext}`;
  const abs = path.join(REFS_DIR, rel);
  await fs.writeFile(abs, file.bytes);
  return { filePath: abs, publicPath: `/refs/${rel}`, mime: file.mime };
}

// Pexels stock fetch (behind PEXELS_API_KEY).
// Returns the bytes; caller persists.
export interface StockResult {
  bytes: Buffer;
  mime: string;
  source: "pexels";
  prompt: string;
  attribution: string;
  width: number;
  height: number;
}

export async function searchStock(query: string, orientation: "landscape" | "portrait" | "square" = "landscape"): Promise<StockResult | null> {
  const key = process.env.PEXELS_API_KEY;
  if (!key) return null;
  const url = `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=1&orientation=${orientation}`;
  const r = await fetch(url, { headers: { Authorization: key } });
  if (!r.ok) return null;
  const j: any = await r.json();
  const photo = j?.photos?.[0];
  if (!photo) return null;
  const dl = photo?.src?.large2x || photo?.src?.large || photo?.src?.original;
  if (!dl) return null;
  const imgResp = await fetch(dl);
  if (!imgResp.ok) return null;
  const ab = await imgResp.arrayBuffer();
  return {
    bytes: Buffer.from(ab),
    mime: "image/jpeg",
    source: "pexels",
    prompt: query,
    attribution: photo.photographer ? `Photo by ${photo.photographer} on Pexels` : "Pexels",
    width: photo.width || 1200,
    height: photo.height || 800,
  };
}

// Gemini generative path (behind GEMINI_API_KEY).
// Returns generated bytes for the requested aspect.
export interface GeneratedResult {
  bytes: Buffer;
  mime: string;
  source: "gemini";
  prompt: string;
  width: number;
  height: number;
}

export async function generateImage(prompt: string, aspectHint: string): Promise<GeneratedResult | null> {
  const key = process.env.GEMINI_API_KEY;
  if (!key) return null;
  // NOTE: This is a seam — exact endpoint shape depends on Gemini Nano Banana 2 release.
  // We attempt the documented imagegen endpoint; failures return null so callers fall back to SVG.
  try {
    const r = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image-preview:generateContent?key=${key}`,
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt + ` Aspect: ${aspectHint}. Photographic, real subject, no text.` }] }],
        }),
      },
    );
    if (!r.ok) return null;
    const j: any = await r.json();
    const part = j?.candidates?.[0]?.content?.parts?.find((p: any) => p?.inlineData?.data);
    if (!part) return null;
    const mime = part.inlineData.mimeType || "image/png";
    const bytes = Buffer.from(part.inlineData.data, "base64");
    const [aw, ah] = parseAspect(aspectHint);
    return { bytes, mime, source: "gemini", prompt, width: aw, height: ah };
  } catch {
    return null;
  }
}

export async function saveBytes(brandSlug: string, bytes: Buffer, mime: string): Promise<SaveResult> {
  await ensureDir();
  const ext = inferExt(mime);
  const rel = `${brandSlug}-${nanoid(10)}${ext}`;
  const abs = path.join(REFS_DIR, rel);
  await fs.writeFile(abs, bytes);
  return { filePath: abs, publicPath: `/refs/${rel}`, mime };
}

function inferExt(mime: string, name?: string): string {
  if (name && /\.(png|jpe?g|webp|gif|avif)$/i.test(name)) return name.match(/\.[a-z0-9]+$/i)![0].toLowerCase();
  if (mime.includes("png")) return ".png";
  if (mime.includes("webp")) return ".webp";
  if (mime.includes("gif")) return ".gif";
  if (mime.includes("avif")) return ".avif";
  return ".jpg";
}

function parseAspect(a: string): [number, number] {
  const m = a.match(/(\d+(?:\.\d+)?):(\d+(?:\.\d+)?)/);
  if (!m) return [1200, 1200];
  const w = parseFloat(m[1]); const h = parseFloat(m[2]);
  const scale = 1200 / Math.max(w, h);
  return [Math.round(w * scale), Math.round(h * scale)];
}
